--- # This file contains all used variables in our task file.
 #Variables added here are either confidential or should be set as environment variables

 # Universal Variables for access keys and secret keys
 aws_region: us-west-1

 # S3 website config variables
 s3_bucket_name: "www-kamiye-com"
 s3_bucket_policy: |
  {
    "Version": "2008-10-17",
    "Id": "PutObjPolicy",
    "Statement": [
      {
        "Sid": "DenyIncorrectEncryptionHeader",
        "Effect": "Deny",
        "Principal": "*",
        "Action": "s3:PutObject",
        "Resource": "arn:aws:s3:::{{s3_bucket_name}}/*",
        "Condition": {
          "StringNotEquals": {
            "s3:x-amz-server-side-encryption": "AES256"
          }
        }
      }
    ]
  }
 s3_website_directory: "website_s3"
  
 s3_website_index_document: "index.html"
 s3_website_error_document: "error.html"

 # Variables for creating AMI
 ami_instance_id: "i-58135ced"

