- name: Create launch config
  ec2_lc:
    name: kamiye-launch-config
    image_id: "{{new_ami.image_id}}"
    region: "{{aws_region}}"
    instance_type: t2.micro

- ec2_asg:
    name: kamiye-asg
    launch_config_name: kamiye-launch-config
    health_check_period: 60
    health_check_type: ELB
    replace_all_instances: yes
    min_size: 2
    max_size: 3
    desired_capacity: 2
    region: "{{aws_region}}"