# Get id of ami created
# Get vpc id of vpc created by cloud formation
# get subnet id of private subnet inside that vpc
#{{cloudformation.stack_resources[2].physical_resource_id}}
- name: Launch Instance Based on Created AMI
